package storage

import (
	"time"

	"telkomsecure-backend/internal/model"
)

// generateInitialSeed creates realistic telco subscribers with purchase history, 10 scan logs, and 30-day retention.
func generateInitialSeed(now time.Time) map[string]*model.Subscriber {
	return make(map[string]*model.Subscriber)
}

func generateLegacyDemoSeed(now time.Time) map[string]*model.Subscriber {
	subs := make(map[string]*model.Subscriber)

	// User 1: Active Pixel 6 Demo
	subs["081299887766"] = &model.Subscriber{
		ID:                   "SUB-081299887766",
		MSISDN:               "081299887766",
		MobileID:             "MOBILE_TEST",
		DeviceModel:          "Google Pixel 6 (Android 14)",
		OSVersion:            "Android 14 / UpsideDownCake",
		PlanName:             "Telkomsel Secure Guard 30 Hari",
		PurchaseTimestamp:    now.Add(-4 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-4 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(26 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(26 * 24 * time.Hour),
		DesyncDays:           0,
		IsActive:             true,
		ActivationCode:       "TK-889123",
		ActivationStatus:     "ACTIVATED",
		KasperskyLicenseKey:  "6KYKJ-65T6T-WMVBD-NNPEG",
		RootStatus:           "CLEAN",
		HookStatus:           "CLEAN",
		BoundIccid:           "89620101998877665544",
		CurrentIccid:         "89620101998877665544",
		SimSlot:              "Slot 1 (Telkomsel Halo)",
		QuarantineCount:      1,
		DeviceMigrationCount: 0,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(26 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-10 * time.Minute),
		CreatedAt:            now.Add(-4 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260922-001",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-4 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "MyTelkomsel App",
				Status:       "ACTIVE",
			},
			{
				ID:           "ORD-20260822-094",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-34 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "MyTelkomsel App",
				Status:       "EXPIRED",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Google Pixel 6", false),
	}

	// User 2: Samsung S24 Ultra Enterprise
	subs["081122334455"] = &model.Subscriber{
		ID:                   "SUB-081122334455",
		MSISDN:               "081122334455",
		MobileID:             "MOB-77A4B190288EFA11",
		DeviceModel:          "Samsung Galaxy S24 Ultra",
		OSVersion:            "Android 14 / OneUI 6.1",
		PlanName:             "Telkomsel Enterprise Protection 1 Tahun",
		PurchaseTimestamp:    now.Add(-60 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-60 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(305 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(305 * 24 * time.Hour),
		DesyncDays:           0,
		IsActive:             true,
		ActivationCode:       "TK-552190",
		ActivationStatus:     "ACTIVATED",
		KasperskyLicenseKey:  "6KYKJ-65T6T-WMVBD-NNPEG",
		RootStatus:           "CLEAN",
		HookStatus:           "CLEAN",
		BoundIccid:           "89620101445566778899",
		CurrentIccid:         "89620101445566778899",
		SimSlot:              "Slot 1 (Telkomsel Halo)",
		QuarantineCount:      0,
		DeviceMigrationCount: 1,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(305 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-1 * time.Hour),
		CreatedAt:            now.Add(-60 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260727-889",
				PackageName:  "Telkomsel Enterprise Protection 1 Tahun",
				PurchasedAt:  now.Add(-60 * 24 * time.Hour),
				DurationDays: 365,
				Price:        240000,
				Channel:      "BSS Corporate Portal",
				Status:       "ACTIVE",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Samsung S24 Ultra", false),
	}

	// User 3: Xiaomi Redmi Note 13 (SMS Failed)
	subs["082199880011"] = &model.Subscriber{
		ID:                   "SUB-082199880011",
		MSISDN:               "082199880011",
		MobileID:             "MOB-1930FA8190BCA771",
		DeviceModel:          "Xiaomi Redmi Note 13",
		OSVersion:            "Android 13 / HyperOS",
		PlanName:             "Telkomsel Secure Guard 30 Hari",
		PurchaseTimestamp:    now.Add(-1 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-1 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(29 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(29 * 24 * time.Hour),
		DesyncDays:           0,
		IsActive:             true,
		ActivationCode:       "TK-441209",
		ActivationStatus:     "SMS_FAILED",
		KasperskyLicenseKey:  "6KYKJ-65T6T-WMVBD-NNPEG",
		RootStatus:           "CLEAN",
		HookStatus:           "CLEAN",
		BoundIccid:           "89620101880011223344",
		CurrentIccid:         "89620101880011223344",
		SimSlot:              "Slot 1 (Telkomsel Prepaid)",
		QuarantineCount:      0,
		DeviceMigrationCount: 0,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(29 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-1 * 24 * time.Hour),
		CreatedAt:            now.Add(-1 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260925-012",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-1 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "USSD *363#",
				Status:       "ACTIVE",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Xiaomi Redmi Note 13", false),
	}

	// User 4: Vivo Y27 (Desync 25 Days)
	subs["081377889900"] = &model.Subscriber{
		ID:                   "SUB-081377889900",
		MSISDN:               "081377889900",
		MobileID:             "MOB-339900AABBCC",
		DeviceModel:          "Vivo Y27 5G",
		OSVersion:            "Android 13 / Funtouch OS",
		PlanName:             "Telkomsel Secure Guard 30 Hari",
		PurchaseTimestamp:    now.Add(-2 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-2 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(28 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(3 * 24 * time.Hour), // Expiring in 3 days instead of 28 days!
		DesyncDays:           25,
		IsActive:             true,
		ActivationCode:       "TK-118944",
		ActivationStatus:     "DESYNC_WARNING",
		KasperskyLicenseKey:  "6KYKJ-65T6T-WMVBD-NNPEG",
		RootStatus:           "CLEAN",
		HookStatus:           "CLEAN",
		BoundIccid:           "89620101778899001122",
		CurrentIccid:         "89620101778899001122",
		SimSlot:              "Slot 1 (Telkomsel Prepaid)",
		QuarantineCount:      0,
		DeviceMigrationCount: 0,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(28 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-3 * time.Hour),
		CreatedAt:            now.Add(-2 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260924-044",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-2 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "MyTelkomsel App",
				Status:       "ACTIVE",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Vivo Y27 5G", false),
	}

	// User 5: Poco X5 Pro (Root & SIM Swap)
	subs["085211223344"] = &model.Subscriber{
		ID:                   "SUB-085211223344",
		MSISDN:               "085211223344",
		MobileID:             "MOB-POCO-X5P-9921",
		DeviceModel:          "Poco X5 Pro 5G",
		OSVersion:            "Android 14 / HyperOS Mod",
		PlanName:             "Telkomsel Secure Guard 30 Hari",
		PurchaseTimestamp:    now.Add(-6 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-6 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(24 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(24 * 24 * time.Hour),
		DesyncDays:           0,
		IsActive:             true,
		ActivationCode:       "TK-774411",
		ActivationStatus:     "ACTIVATED",
		KasperskyLicenseKey:  "6KYKJ-65T6T-WMVBD-NNPEG",
		RootStatus:           "ROOT_DETECTED",
		HookStatus:           "HOOK_DETECTED",
		BoundIccid:           "89620101554433221100",
		CurrentIccid:         "89620101999988887777", // SIM Swap
		SimSlot:              "Slot 1 (Telkomsel Prepaid)",
		QuarantineCount:      2,
		DeviceMigrationCount: 0,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(24 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-30 * time.Minute),
		CreatedAt:            now.Add(-6 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260920-077",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-6 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "MyTelkomsel App",
				Status:       "ACTIVE",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Poco X5 Pro 5G", true),
	}

	// User 6: Expired Demo User (081200000000)
	subs["081200000000"] = &model.Subscriber{
		ID:                   "SUB-081200000000",
		MSISDN:               "081200000000",
		MobileID:             "MOB-EXP-081200000000",
		DeviceModel:          "Google Pixel 6 (Android 14)",
		OSVersion:            "Android 14 / UpsideDownCake",
		PlanName:             "Telkomsel Secure Guard 30 Hari",
		PurchaseTimestamp:    now.Add(-35 * 24 * time.Hour),
		ActivePeriodStart:    now.Add(-35 * 24 * time.Hour),
		ActivePeriodEnd:      now.Add(-5 * 24 * time.Hour),
		KasperskyExpiryDate:  now.Add(-5 * 24 * time.Hour),
		DesyncDays:           0,
		IsActive:             false,
		ActivationCode:       "TK-000000",
		ActivationStatus:     "EXPIRED",
		KasperskyLicenseKey:  "",
		RootStatus:           "CLEAN",
		HookStatus:           "CLEAN",
		BoundIccid:           "89620101000000001122",
		CurrentIccid:         "89620101000000001122",
		SimSlot:              "Slot 1 (Telkomsel Prepaid)",
		QuarantineCount:      0,
		DeviceMigrationCount: 0,
		DataRetentionDays:    30,
		RetentionExpiresAt:   now.Add(-5 * 24 * time.Hour),
		IsArchived:           false,
		LastCheckedAt:        now.Add(-1 * 24 * time.Hour),
		CreatedAt:            now.Add(-35 * 24 * time.Hour),
		PurchaseHistory: []model.PackagePurchaseRecord{
			{
				ID:           "ORD-20260824-001",
				PackageName:  "Telkomsel Secure Guard 30 Hari",
				PurchasedAt:  now.Add(-35 * 24 * time.Hour),
				DurationDays: 30,
				Price:        25000,
				Channel:      "MyTelkomsel App",
				Status:       "EXPIRED",
			},
		},
		RecentScanLogs: generateSampleScanLogs(now, "Google Pixel 6", false),
	}

	return subs
}

// generateSampleScanLogs creates exactly 10 comprehensive scan records across Kaspersky modules.
func generateSampleScanLogs(now time.Time, modelName string, hasThreats bool) []model.ScanLog {
	logs := []model.ScanLog{
		{
			ID:           "SCAN-101",
			Module:       "ANTIVIRUS",
			ScanType:     "QUICK_SCAN",
			Result:       "CLEAN",
			ItemsScanned: 1840,
			ThreatsFound: 0,
			Details:      "Kaspersky Engine memindai sistem dan memori kerja. Tidak ada malware ditemukan.",
			Timestamp:    now.Add(-15 * time.Minute),
		},
		{
			ID:           "SCAN-102",
			Module:       "WEB_PROTECTION",
			ScanType:     "REALTIME_MONITOR",
			Result:       "CLEAN",
			ItemsScanned: 42,
			ThreatsFound: 0,
			Details:      "Kaspersky Web Filter memverifikasi trafik DNS & browser Chrome.",
			Timestamp:    now.Add(-1 * time.Hour),
		},
		{
			ID:           "SCAN-103",
			Module:       "SIM_WATCH",
			ScanType:     "HARDWARE_CHECK",
			Result:       map[bool]string{true: "THREAT_BLOCKED", false: "CLEAN"}[hasThreats],
			ItemsScanned: 1,
			ThreatsFound: map[bool]int{true: 1, false: 0}[hasThreats],
			Details:      map[bool]string{true: "Deteksi ICCID mismatch! Kartu SIM fisik telah diganti.", false: "Kartu SIM terdaftar resmi di slot utama."}[hasThreats],
			Timestamp:    now.Add(-2 * time.Hour),
		},
		{
			ID:           "SCAN-104",
			Module:       "RASP",
			ScanType:     "TAMPER_CHECK",
			Result:       map[bool]string{true: "TAMPER_PREVENTED", false: "CLEAN"}[hasThreats],
			ItemsScanned: 14,
			ThreatsFound: map[bool]int{true: 1, false: 0}[hasThreats],
			Details:      map[bool]string{true: "BlackWall RASP mendeteksi socket Frida / Magisk su binary.", false: "Integritas binary APK valid, tidak ada hooking dynamic."}[hasThreats],
			Timestamp:    now.Add(-4 * time.Hour),
		},
		{
			ID:           "SCAN-105",
			Module:       "ANTIVIRUS",
			ScanType:     "FILE_DOWNLOAD",
			Result:       map[bool]string{true: "FILE_QUARANTINED", false: "CLEAN"}[hasThreats],
			ItemsScanned: 1,
			ThreatsFound: map[bool]int{true: 1, false: 0}[hasThreats],
			Details:      map[bool]string{true: "File EICAR test signature diunduh ke folder Download dan langsung diisolasi.", false: "File lampiran aman dari trojan dan ransomware."}[hasThreats],
			Timestamp:    now.Add(-8 * time.Hour),
		},
		{
			ID:           "SCAN-106",
			Module:       "NETWORK_ATTACK_BLOCKER",
			ScanType:     "WI-FI_INSPECTION",
			Result:       "CLEAN",
			ItemsScanned: 1,
			ThreatsFound: 0,
			Details:      "Wi-Fi SSID terlindungi dengan enkripsi WPA3, tidak ada serangan Man-in-the-Middle (MitM).",
			Timestamp:    now.Add(-12 * time.Hour),
		},
		{
			ID:           "SCAN-107",
			Module:       "ANTIVIRUS",
			ScanType:     "FULL_SCAN",
			Result:       "CLEAN",
			ItemsScanned: 15420,
			ThreatsFound: 0,
			Details:      "Pemindaian menyeluruh internal storage selesai dalam 1 menit 12 detik.",
			Timestamp:    now.Add(-24 * time.Hour),
		},
		{
			ID:           "SCAN-108",
			Module:       "WEB_PROTECTION",
			ScanType:     "ANTI-PHISHING",
			Result:       "CLEAN",
			ItemsScanned: 88,
			ThreatsFound: 0,
			Details:      "Pengecekan database reputasi Kaspersky Security Network (KSN) aktif.",
			Timestamp:    now.Add(-30 * time.Hour),
		},
		{
			ID:           "SCAN-109",
			Module:       "APP_CONTROL",
			ScanType:     "PERMISSION_AUDIT",
			Result:       "CLEAN",
			ItemsScanned: 64,
			ThreatsFound: 0,
			Details:      "Audit izin akses SMS, Kamera, dan Lokasi pada semua aplikasi pihak ketiga.",
			Timestamp:    now.Add(-36 * time.Hour),
		},
		{
			ID:           "SCAN-110",
			Module:       "SYSTEM_AUDIT",
			ScanType:     "HEALTH_CHECK",
			Result:       "CLEAN",
			ItemsScanned: 5,
			ThreatsFound: 0,
			Details:      "Basis data antivirus Kaspersky v2026.09 terpasang dan diperbarui otomatis.",
			Timestamp:    now.Add(-48 * time.Hour),
		},
	}
	return logs
}
