package storage

import (
	"time"

	"telkomsecure-backend/internal/model"
)

// generateSampleThreats generates initial security threat telemetry with GIS coordinates for the SOC dashboard.
func generateSampleThreats(now time.Time) []model.ThreatEvent {
	return []model.ThreatEvent{
		{
			ID:          "THR-20261003-001",
			MobileID:    "MOBILE_TEST",
			MSISDN:      "081299887766",
			ThreatType:  "PHISHING",
			Target:      "https://my-telkomsel-poin-klaim.xyz/login",
			Severity:    "CRITICAL",
			Description: "Percobaan akses phishing credential harvesting Telkomsel Poin diblokir oleh Web Filter.",
			ActionTaken: "BLOCKED",
			Latitude:    -6.2088,
			Longitude:   106.8456,
			City:        "Jakarta Pusat",
			LocationTag: "Kawasan Rasuna Said, Jakarta",
			NetworkType: "Telkomsel 5G",
			Timestamp:   now.Add(-15 * time.Minute),
		},
		{
			ID:          "THR-20261003-002",
			MobileID:    "MOBILE_TEST",
			MSISDN:      "081299887766",
			ThreatType:  "MALWARE",
			Target:      "/storage/emulated/0/Download/apk_undangan_pernikahan.apk",
			Severity:    "CRITICAL",
			Description: "Trojan-Banker.AndroidOS.FakeDoc berhasil diidentifikasi dan dikarantina.",
			ActionTaken: "ISOLATED",
			Latitude:    -6.1751,
			Longitude:   106.8650,
			City:        "Jakarta Pusat",
			LocationTag: "Cempaka Putih, Jakarta",
			NetworkType: "WiFi - Cafe_Net_Free",
			Timestamp:   now.Add(-45 * time.Minute),
		},
		{
			ID:          "THR-20261003-003",
			MobileID:    "MOBILE_S24_02",
			MSISDN:      "081122334455",
			ThreatType:  "WIFI",
			Target:      "SSID: Orbit_Free_Public (Evil Twin)",
			Severity:    "HIGH",
			Description: "Rogue Wi-Fi AP terdeteksi memalsukan Telkomsel Orbit tanpa enkripsi WPA.",
			ActionTaken: "BLOCKED",
			Latitude:    -6.9175,
			Longitude:   107.6191,
			City:        "Bandung",
			LocationTag: "Dago Atas, Bandung",
			NetworkType: "WiFi - Rogue AP",
			Timestamp:   now.Add(-2 * time.Hour),
		},
		{
			ID:          "THR-20261003-004",
			MobileID:    "MOBILE_ROG_03",
			MSISDN:      "085233445566",
			ThreatType:  "SIM_WATCH",
			Target:      "SIM Slot 1 (ICCID Changed)",
			Severity:    "HIGH",
			Description: "Deteksi pergantian SIM Card tanpa otorisasi. Sinyal proteksi SIM Watch dikirimkan ke SOC.",
			ActionTaken: "REPORTED",
			Latitude:    -7.2575,
			Longitude:   112.7521,
			City:        "Surabaya",
			LocationTag: "Gubeng, Surabaya",
			NetworkType: "Cellular - Telkomsel 4G",
			Timestamp:   now.Add(-4 * time.Hour),
		},
		{
			ID:          "THR-20261003-005",
			MobileID:    "MOBILE_IP15_04",
			MSISDN:      "082155667788",
			ThreatType:  "PHISHING",
			Target:      "http://bca-klik-secure-update.com/auth",
			Severity:    "CRITICAL",
			Description: "Situs perbankan palsu dicegah oleh Kaspersky Web Protection SDK.",
			ActionTaken: "BLOCKED",
			Latitude:    3.5952,
			Longitude:   98.6722,
			City:        "Medan",
			LocationTag: "Kesawan, Medan",
			NetworkType: "Telkomsel 5G",
			Timestamp:   now.Add(-7 * time.Hour),
		},
		{
			ID:          "THR-20261003-006",
			MobileID:    "MOBILE_VIVO_05",
			MSISDN:      "081377889900",
			ThreatType:  "MALWARE",
			Target:      "/storage/emulated/0/Download/Surat_Tilang_Elektronik.apk",
			Severity:    "CRITICAL",
			Description: "Malware pencuri SMS OTP SMS.AndroidOS.Agent diisolasi oleh antivirus engine.",
			ActionTaken: "ISOLATED",
			Latitude:    -8.6705,
			Longitude:   115.2126,
			City:        "Denpasar",
			LocationTag: "Sanur, Denpasar, Bali",
			NetworkType: "WiFi - Hotel_Guest",
			Timestamp:   now.Add(-11 * time.Hour),
		},
		{
			ID:          "THR-20261003-007",
			MobileID:    "MOBILE_POCO_06",
			MSISDN:      "085211223344",
			ThreatType:  "RASP",
			Target:      "Magisk SU Binary / System Tampered",
			Severity:    "HIGH",
			Description: "Injeksi root binary terdeteksi. BlackWall RASP mengamankan keystore dan memutus sesi perbankan.",
			ActionTaken: "REPORTED",
			Latitude:    -7.7956,
			Longitude:   110.3695,
			City:        "Yogyakarta",
			LocationTag: "Malioboro, Yogyakarta",
			NetworkType: "Telkomsel 4G LTE",
			Timestamp:   now.Add(-18 * time.Hour),
		},
		{
			ID:          "THR-20261003-008",
			MobileID:    "MOBILE_OPPO_07",
			MSISDN:      "081288776655",
			ThreatType:  "WIFI",
			Target:      "SSID: Bandara_Free_Wifi (Unencrypted)",
			Severity:    "MEDIUM",
			Description: "Jaringan Wi-Fi publik tanpa enkripsi WPA2/WPA3. Potensi intersepsi ARP Spoofing.",
			ActionTaken: "REPORTED",
			Latitude:    -5.1477,
			Longitude:   119.4327,
			City:        "Makassar",
			LocationTag: "Sultan Hasanuddin, Makassar",
			NetworkType: "WiFi - Airport_Open",
			Timestamp:   now.Add(-23 * time.Hour),
		},
	}
}
