apply plugin: 'com.android.library'

android {
    useLibrary 'org.apache.http.legacy'
}

apply from: "${gKavSdkExampleProject.getProjectDir()}/gradle-common/features-android-closure-defaults.gradle"
apply from: "${gKavSdkExampleProject.getProjectDir()}/gradle/features-dependencies-closure-defaults.gradle"


