apply plugin: 'com.android.library'

apply from: "${gKavSdkExampleProject.getProjectDir()}/gradle-common/features-android-closure-defaults.gradle"
apply from: "${gKavSdkExampleProject.getProjectDir()}/gradle/features-dependencies-closure-defaults.gradle"

dependencies {
    //debugCompileOnly 'com.squareup.leakcanary:leakcanary-android:' + "2.7"
}